import { defineCollection, z } from "astro:content";

import { glob } from "astro/loaders";

const blog = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/data/blog" }),
  schema: z.object({
    title: z.string(),
    published: z.date(),
    url: z.string(),
    draft: z.boolean().optional(),
    description: z.string().optional(),
    tags: z.array(z.string()).optional(),
    category: z.string().optional(),
    audioUrl: z.string().optional(),
    // Social card override: a path under public/, e.g. "/post-pics/2026/01/thing.webp".
    // Leave unset to use the card generated by src/pages/og/[...slug].webp.ts.
    image: z.string().optional(),
    imageAlt: z.string().optional(),
  }),
});

export const collections = { blog };
